// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TILECACHE_CHARTBOX_IO_FLATBUFFER_H_
#define FLATBUFFERS_GENERATED_TILECACHE_CHARTBOX_IO_FLATBUFFER_H_

#include "flatbuffers/flatbuffers.h"

namespace chartbox {
namespace io {
namespace flatbuffer {

struct Location;

struct TileCache;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Location FLATBUFFERS_FINAL_CLASS {
 private:
  float easting_;
  float northing_;

 public:
  Location() {
    memset(static_cast<void *>(this), 0, sizeof(Location));
  }
  Location(float _easting, float _northing)
      : easting_(flatbuffers::EndianScalar(_easting)),
        northing_(flatbuffers::EndianScalar(_northing)) {
  }
  float easting() const {
    return flatbuffers::EndianScalar(easting_);
  }
  float northing() const {
    return flatbuffers::EndianScalar(northing_);
  }
};
FLATBUFFERS_STRUCT_END(Location, 8);

struct TileCache FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORIGIN = 4,
    VT_PRECISION = 6,
    VT_DIMENSION = 8,
    VT_DATA = 10
  };
  const Location *origin() const {
    return GetStruct<const Location *>(VT_ORIGIN);
  }
  float precision() const {
    return GetField<float>(VT_PRECISION, 0.0f);
  }
  uint32_t dimension() const {
    return GetField<uint32_t>(VT_DIMENSION, 0);
  }
  const flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Location>(verifier, VT_ORIGIN) &&
           VerifyField<float>(verifier, VT_PRECISION) &&
           VerifyField<uint32_t>(verifier, VT_DIMENSION) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct TileCacheBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_origin(const Location *origin) {
    fbb_.AddStruct(TileCache::VT_ORIGIN, origin);
  }
  void add_precision(float precision) {
    fbb_.AddElement<float>(TileCache::VT_PRECISION, precision, 0.0f);
  }
  void add_dimension(uint32_t dimension) {
    fbb_.AddElement<uint32_t>(TileCache::VT_DIMENSION, dimension, 0);
  }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(TileCache::VT_DATA, data);
  }
  explicit TileCacheBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TileCacheBuilder &operator=(const TileCacheBuilder &);
  flatbuffers::Offset<TileCache> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TileCache>(end);
    return o;
  }
};

inline flatbuffers::Offset<TileCache> CreateTileCache(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Location *origin = 0,
    float precision = 0.0f,
    uint32_t dimension = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data = 0) {
  TileCacheBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_dimension(dimension);
  builder_.add_precision(precision);
  builder_.add_origin(origin);
  return builder_.Finish();
}

inline flatbuffers::Offset<TileCache> CreateTileCacheDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Location *origin = 0,
    float precision = 0.0f,
    uint32_t dimension = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return chartbox::io::flatbuffer::CreateTileCache(
      _fbb,
      origin,
      precision,
      dimension,
      data__);
}

inline const chartbox::io::flatbuffer::TileCache *GetTileCache(const void *buf) {
  return flatbuffers::GetRoot<chartbox::io::flatbuffer::TileCache>(buf);
}

inline const chartbox::io::flatbuffer::TileCache *GetSizePrefixedTileCache(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<chartbox::io::flatbuffer::TileCache>(buf);
}

inline bool VerifyTileCacheBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<chartbox::io::flatbuffer::TileCache>(nullptr);
}

inline bool VerifySizePrefixedTileCacheBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<chartbox::io::flatbuffer::TileCache>(nullptr);
}

inline void FinishTileCacheBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<chartbox::io::flatbuffer::TileCache> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTileCacheBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<chartbox::io::flatbuffer::TileCache> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace flatbuffer
}  // namespace io
}  // namespace chartbox

#endif  // FLATBUFFERS_GENERATED_TILECACHE_CHARTBOX_IO_FLATBUFFER_H_
